#cloud-config

users:
- name: etoa
  lock_passwd: true
  shell: /bin/bash

package_upgrade: true
package_update: true
packages:
- apache2
- php-fpm
- php-xml
- php-gd
- php-curl
- php-mysql
- php-zip
- php-mbstring
- composer
- unzip
- mysql-server
- git
- htop
- vim
- build-essential
- cmake
- libmysql++-dev
- libboost-all-dev
- certbot
- python-certbot-apache
- postfix

write_files:
- content: |
    <VirtualHost *:80>
            ServerName ${hostname}
            ServerAdmin mail@etoa.ch
            DocumentRoot /var/www/etoa/htdocs
            ErrorLog $${APACHE_LOG_DIR}/etoa_error.log
            CustomLog $${APACHE_LOG_DIR}/etoa_access.log combined
    </VirtualHost>
  path: /etc/apache2/sites-available/etoa.conf
- content: |
    <IfModule !mod_php7.c>
    <IfModule proxy_fcgi_module>
        # Enable http authorization headers
        <IfModule setenvif_module>
        SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
        </IfModule>
        <FilesMatch ".+\.ph(ar|p|tml)$">
            SetHandler "proxy:unix:/run/php/php7.2-etoa-fpm.sock|fcgi://localhost"
        </FilesMatch>
        <FilesMatch ".+\.phps$">
            Require all denied
        </FilesMatch>
        <FilesMatch "^\.ph(ar|p|ps|tml)$">
            Require all denied
        </FilesMatch>
    </IfModule>
    </IfModule>
  path: /etc/apache2/conf-available/php7.2-etoa-fpm.conf
- content: |
    [etoa]
    user = etoa
    group = etoa
    listen = /run/php/php7.2-etoa-fpm.sock
    listen.owner = www-data
    listen.group = www-data
    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3
  path: /etc/php/7.2/fpm/pool.d/etoa.conf
- content: |
    auto eth0:1
    iface eth0:1 inet static
        address ${public_ip}
        netmask 32
  path: /etc/network/interfaces.d/60-my-floating-ip.cfg
- content: |
    SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
    CREATE DATABASE IF NOT EXISTS etoa;
    GRANT USAGE ON *.* TO etoa@localhost IDENTIFIED BY 'etoa';
    GRANT ALL PRIVILEGES ON etoa.* TO etoa@localhost;
    FLUSH PRIVILEGES;
  path: /root/init.sql

bootcmd:
- ip addr add ${public_ip} dev eth0
- mkdir -p /mnt/data; mount ${data_disk} /mnt/data
- mkdir -p /var/lib/mysql /mnt/data/mysql; mount --bind /mnt/data/mysql /var/lib/mysql
- mkdir -p /var/www /mnt/data/www; mount --bind /mnt/data/www /var/www

runcmd:
 - if [ -d /var/www/etoa ]; then cd /var/www/etoa; git checkout ${webapp_branch}; else git clone --branch ${webapp_branch} https://github.com/etoa/etoa-gui.git /var/www/etoa; fi
 - chown -R etoa:etoa /var/www/etoa
 - su etoa -s /bin/bash -c "cd /var/www/etoa; composer install"
 - a2enmod proxy_fcgi setenvif
 - a2enconf php7.2-etoa-fpm
 - a2ensite etoa
 - a2dissite 000-default
 - systemctl reload apache2
 - rm /etc/php/7.2/fpm/pool.d/www.conf
 - systemctl reload php7.2-fpm.service
 - mysql -u root < /root/init.sql
 - certbot --apache --agree-tos -m mail@etoa.ch -d ${hostname} --non-interactive --redirect
 - su etoa -s /bin/bash -c "cd /var/www/etoa/eventhandler && cmake . && make"
